### ISSUE TITLE
Copy of Initial Readiness Checklist from original repo

### ISSUE THREAD

**Issue by JustinKuli** [JustinKuli/governance-policy-nucleus#1]
The current README says "This repository is under construction, and not yet ready for use." So what is necessary to add, before we can remove that?

- [x] NamespaceSelector with LabelSelector
- [x] Common function(s) for emitting compliance events
- [ ] Documentation on how to develop inside this repository
- [ ] Documentation on how to develop something with this module
- [ ] A policy controller (not the FakePolicy one) that uses this module as an example
